apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  labels:
    account: airflow
---
###############################################################################
# airflow-postgres
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  labels:
    app: airflow-postgres
    service: airflow-postgres
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: airflow-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres-v1
  labels:
    app: airflow-postgres
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: airflow-postgres
        version: v1
    spec:
      serviceAccountName: airflow
      containers:
      - name: airflow-postgres
        image: registry.redhat.io/rhscl/postgresql-95-rhel7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: POSTGRESQL_USER
          value: airflow
        - name: POSTGRESQL_PASSWORD
          value: airflow
        - name: POSTGRESQL_DATABASE
          value: airflow
        volumeMounts:
        - name: postgres-db-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-db-volume
        emptyDir: {}
---
###############################################################################
# airflow-redis
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-redis
  labels:
    app: airflow-redis
    service: airflow-redis
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: airflow-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-redis-v1
  labels:
    app: airflow-redis
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-redis
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        description: "NoSQL DB"
        iconClass: "icon-redis"
        tags: "database,nosql"
      labels:
        app: airflow-redis
        version: v1
    spec:
      serviceAccountName: airflow
      containers:
        - name: airflow-redis
          image: registry.redhat.io/rhscl/redis-5-rhel7@13309f63e319
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              protocol: TCP
          env:
            - name: REDIS_PASSWORD
              value: BadPassword1234$
          volumeMounts:
            - name: redis-db-volume
              mountPath: /var/lib/redis/data
      volumes:
        - name: redis-db-volume
          emptyDir: {}
---
###############################################################################
# airflow-webserver
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow-webserver
    service: airflow-webserver
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: airflow-webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver-v1
  labels:
    app: airflow-webserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: airflow-webserver
        version: v1
    spec:
      serviceAccountName: airflow
      containers:
      - name: "airflow-webserver"
        image: "quay.io/opendatahub/docker-airflow@sha256:7988768a9a701d1e9ac1937948d44c7191cee913883b6491d2d936630434225a"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: CeleryExecutor
          - name: AIRFLOW__CORE__EXECUTOR
            value: CeleryExecutor
          - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
            value: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
          - name: AIRFLOW__CELERY__RESULT_BACKEND
            value: db+postgresql://airflow:airflow@airflow-postgres/airflow
          - name: AIRFLOW__CELERY__BROKER_URL
            value: redis://:@airflow-redis:6379/0
          - name: AIRFLOW__CORE__FERNET_KEY
            value: ""
          - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
            value: "true"
          - name: AIRFLOW__CORE__LOAD_EXAMPLES
            value: "true"
---
